<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Analyzers apply to every project. -->
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Jellyfin.Controller" Version="12.1.0" />
    <PackageVersion Include="Jellyfin.Model" Version="12.1.0" />
    <PackageVersion Include="Meziantou.Framework.Win32.Jobs" Version="4.0.3" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>
