using Jellyfin.Plugin.HwProbe.Core.Devices;
using Jellyfin.Plugin.HwProbe.Core.Ffmpeg;
using Jellyfin.Plugin.HwProbe.Core.Model;
using Jellyfin.Plugin.HwProbe.Core.Pipeline;
using Jellyfin.Plugin.HwProbe.Core.Verdict;

namespace Jellyfin.Plugin.HwProbe.Core.Probes;

/// <summary>The bare device open, the one probe not generated by EncodingHelper.</summary>
public static class DeviceOpenProbe
{
    /// <summary>Returns the device-open argument string, or null when the backend has no device to open.</summary>
    /// <param name="type">The backend.</param>
    /// <param name="device">Render node or adapter index.</param>
    /// <param name="os">The host OS.</param>
    /// <returns>The arguments, or null for v4l2m2m.</returns>
    public static string? Arguments(HwType type, string device, HostOs os)
    {
        // Mirrors EncoderValidator.CheckVaapiDeviceByDriverName: init only, no input or output.
        const string Prefix = "-v verbose -hide_banner -init_hw_device ";
        return type switch
        {
            HwType.vaapi => Prefix + $"vaapi=va:{device}",
            HwType.qsv when os == HostOs.Windows => Prefix + $"d3d11va=dx11:{device} -init_hw_device qsv=qs@dx11",
            HwType.qsv => Prefix + $"vaapi=va:{device} -init_hw_device qsv=qs@va",
            HwType.nvenc => Prefix + $"cuda=cu:{device}",
            HwType.amf => Prefix + $"d3d11va=dx11:{device}",
            HwType.videotoolbox => Prefix + "videotoolbox=vt",
            HwType.rkmpp => Prefix + "rkmpp=rk",
            HwType.v4l2m2m or HwType.none => null,
            _ => throw new ArgumentOutOfRangeException(nameof(type), type, null),
        };
    }

    /// <summary>Classifies a device-open run.</summary>
    /// <param name="type">The backend.</param>
    /// <param name="result">The run result.</param>
    /// <returns>The outcome and any identified driver.</returns>
    /// <remarks>ffmpeg always exits non-zero here (no output), so only stderr is judged.</remarks>
    public static DeviceOpenResult Evaluate(HwType type, FfmpegRunResult result)
    {
        ArgumentNullException.ThrowIfNull(result);

        if (result.Status == FfmpegRunStatus.TimedOut)
        {
            return new DeviceOpenResult(ProbeOutcome.Timeout, VaapiDriver.Other, null);
        }

        var stderr = result.Stderr;
        if (type is HwType.vaapi || (type is HwType.qsv && stderr.Contains(StderrMarkers.VaapiDriverPrefix, StringComparison.Ordinal)))
        {
            var outcome = VerdictEvaluator.EvaluateDeviceOpen(result, StderrMarkers.VaapiDriverPrefix);
            var driverLine = DriverLine(stderr);
            var driver = StderrMarkers.VaapiDrivers.FirstOrDefault(d => stderr.Contains(d.Name, StringComparison.Ordinal)).Driver;
            if (outcome != ProbeOutcome.Pass || type is HwType.vaapi)
            {
                return new DeviceOpenResult(outcome, driver, driverLine);
            }

            // QSV derives from the VAAPI parent; the parent opening is not enough.
            return new DeviceOpenResult(GenericOutcome(stderr), driver, driverLine);
        }

        return new DeviceOpenResult(GenericOutcome(stderr), VaapiDriver.Other, null);
    }

    /// <summary>Classifies a device open with no success line: any failure marker fails it.</summary>
    /// <param name="stderr">Captured stderr.</param>
    /// <returns>The outcome.</returns>
    /// <remarks>Observed with homebrew ffmpeg 9.0.2: a failed init logs "Device creation failed"; a good one doesn't.</remarks>
    private static ProbeOutcome GenericOutcome(string stderr)
    {
        if (StderrMarkers.PermissionDenied.Any(m => stderr.Contains(m, StringComparison.Ordinal)))
        {
            return ProbeOutcome.PermissionDenied;
        }

        return StderrMarkers.DeviceUnavailable.Any(m => stderr.Contains(m, StringComparison.Ordinal)) ? ProbeOutcome.DeviceUnavailable : ProbeOutcome.Pass;
    }

    /// <summary>Extracts the VAAPI driver line.</summary>
    /// <param name="stderr">Captured stderr.</param>
    /// <returns>The driver description, or null.</returns>
    private static string? DriverLine(string stderr)
    {
        var start = stderr.IndexOf(StderrMarkers.VaapiDriverPrefix, StringComparison.Ordinal);
        if (start < 0)
        {
            return null;
        }

        start += StderrMarkers.VaapiDriverPrefix.Length;
        var end = stderr.IndexOf('\n', start);
        return stderr[start..(end < 0 ? stderr.Length : end)].Trim().TrimEnd('.');
    }
}
