using System.Globalization;

namespace Jellyfin.Plugin.HwProbe.Core.Probes;

/// <summary>Assembles a full probe command line around generated arguments.</summary>
/// <remarks>
/// The wrapper (fixture input, frame limit, null muxer, progress) is synthesized; upstream has no self-test
/// to copy. Debug logging is needed for the decoder's get_format line, the only hardware confirmation
/// some decoders print.
/// </remarks>
public static class ProbeCommandLine
{
    /// <summary>Builds the argument string.</summary>
    /// <param name="args">Arguments generated by EncodingHelper.</param>
    /// <param name="fixturePath">The input clip.</param>
    /// <param name="frames">Frames to process.</param>
    /// <returns>The ffmpeg argument string.</returns>
    public static string Build(ProbeArguments args, string fixturePath, int frames)
    {
        ArgumentNullException.ThrowIfNull(args);

        return string.Create(
            CultureInfo.InvariantCulture,
            $"-hide_banner -v debug -nostats -progress pipe:1 {args.InputArgs} -i \"{fixturePath}\" -frames:v {frames}{args.FilterArgs} -c:v {args.VideoEncoder} -an -f null -")
            .Replace("  ", " ", StringComparison.Ordinal);
    }
}
