#!/usr/bin/env python3
"""Writes the third-party notices for the libraries the plugin and the CLI ship.

Reads each project's restore output (obj/project.assets.json) for the NuGet packages with runtime assemblies, and
each package's .nuspec in the NuGet cache for its licence and home page. Writes THIRD-PARTY-NOTICES.md and the
plugin's libraries.json, which the Help tab lists. --check fails when either file is out of date.
"""

import argparse
import json
import os
import sys
import xml.etree.ElementTree as ElementTree

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from package import PLUGIN_LIBRARIES  # noqa: E402
PRODUCTS = [("Plugin", "src/HwProbe.Plugin"), ("CLI", "src/HwProbe.Cli")]
NOTICES = os.path.join(ROOT, "THIRD-PARTY-NOTICES.md")
LIBRARIES = os.path.join(ROOT, "src/HwProbe.Plugin/Configuration/libraries.json")


def packages(project, shipped=None):
    """Returns (id, version) of each package that puts an assembly in the project's output, from its restore output; only those whose assemblies are in shipped, when given."""
    path = os.path.join(ROOT, project, "obj", "project.assets.json")
    if not os.path.exists(path):
        sys.exit(f"{path} is missing; run dotnet restore first")
    with open(path, encoding="utf-8") as f:
        assets = json.load(f)
    target = assets["targets"]["net10.0"]
    found = []
    for key, entry in target.items():
        runtime = [name for name in entry.get("runtime", {}) if not name.endswith("_._")]
        if entry.get("type") == "package" and runtime and (shipped is None or any(os.path.basename(name) in shipped for name in runtime)):
            name, version = key.split("/")
            found.append((name, version))
    return sorted(found, key=lambda p: p[0].lower())


def nuspec(name, version):
    """Returns the licence, its text when the package ships it as a file, and the home page, from the package's .nuspec."""
    folder = os.path.join(os.path.expanduser(os.environ.get("NUGET_PACKAGES", "~/.nuget/packages")), name.lower(), version.lower())
    with open(os.path.join(folder, name.lower() + ".nuspec"), encoding="utf-8") as f:
        text = f.read()
    # Each nuspec uses its own schema namespace; matching on local names reads them all.
    metadata = next(e for e in ElementTree.fromstring(text).iter() if e.tag.endswith("metadata"))
    fields = {e.tag.split("}")[-1]: e for e in metadata}
    license_element = fields.get("license")
    license_text = None
    if license_element is not None and license_element.get("type") == "expression":
        license_name = license_element.text.strip()
    elif license_element is not None:
        license_name = "See licence text"
        with open(os.path.join(folder, license_element.text.strip()), encoding="utf-8-sig") as f:
            license_text = f.read().strip()
    else:
        license_name = fields["licenseUrl"].text.strip()
    url = fields["projectUrl"].text.strip() if "projectUrl" in fields else fields["repository"].get("url")
    return license_name, license_text, url


def build():
    """Returns the notices file's text and the plugin's library list."""
    lines = [
        "# Third-party notices",
        "",
        "Libraries shipped in the HwProbe plugin and the hwprobe CLI. Generated by `scripts/notices.py` from the projects' NuGet restore output; the plugin's list is also on its Help tab. The CLI is self-contained, so it also carries the .NET runtime (MIT, https://github.com/dotnet/runtime). Assets are listed in `assets/NOTICE.md`.",
    ]
    texts = {}
    libraries = []
    for product, project in PRODUCTS:
        lines += ["", f"## {product}", "", "| Library | Version | Licence |", "|---|---|---|"]
        for name, version in packages(project, PLUGIN_LIBRARIES if product == "Plugin" else None):
            license_name, license_text, url = nuspec(name, version)
            shown = f"[{license_name}](#{name.lower().replace('.', '')})" if license_text else license_name
            lines.append(f"| [{name}]({url}) | {version} | {shown} |")
            if license_text:
                texts[name] = license_text
            if product == "Plugin":
                libraries.append({"Name": name, "Version": version, "License": license_name, "Url": url})
    if texts:
        lines += ["", "## Licence texts"]
        for name, text in sorted(texts.items()):
            lines += ["", f"### {name}", "", "```", text, "```"]
    return "\n".join(lines) + "\n", json.dumps(libraries, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail instead of writing when a file is out of date.")
    args = parser.parse_args()
    notices, libraries = build()
    stale = []
    for path, text in ((NOTICES, notices), (LIBRARIES, libraries)):
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current == text:
            continue
        if args.check:
            stale.append(os.path.relpath(path, ROOT))
        else:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
    if stale:
        sys.exit(f"out of date: {', '.join(stale)}; run python3 scripts/notices.py")


if __name__ == "__main__":
    main()
